use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ThreatCorrelation {
    pub id: String,
    pub cve_id: String,
    pub title: String,
    pub cvss_score: f64,
    pub severity: String,
    pub affected_component: String,
    pub affected_version: String,
    pub kev_listed: bool,
    pub mitre_tactic: String,
    pub mitre_technique: String,
    pub mitre_technique_id: String,
    pub description: String,
    pub published: String,
    pub references: Vec<String>,
}

pub struct ThreatFeedEngine;

impl ThreatFeedEngine {
    pub fn get_correlated_threats() -> Vec<ThreatCorrelation> {
        vec![
            ThreatCorrelation {
                id: "tc-001".into(),
                cve_id: "CVE-2024-3094".into(),
                title: "XZ Utils Backdoor — Supply-Chain Compromise".into(),
                cvss_score: 10.0,
                severity: "CRITICAL".into(),
                affected_component: "xz-utils".into(),
                affected_version: "5.6.0–5.6.1".into(),
                kev_listed: true,
                mitre_tactic: "Initial Access".into(),
                mitre_technique: "Supply Chain Compromise".into(),
                mitre_technique_id: "T1195.002".into(),
                description: "Malicious code was discovered in the upstream xz/liblzma tarballs, enabling remote code execution through sshd via systemd. State-sponsored threat actor Jia Tan inserted obfuscated binary test fixtures.".into(),
                published: "2024-03-29".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2024-3094".into()],
            },
            ThreatCorrelation {
                id: "tc-002".into(),
                cve_id: "CVE-2024-1086".into(),
                title: "Linux Kernel nf_tables Use-After-Free LPE".into(),
                cvss_score: 7.8,
                severity: "HIGH".into(),
                affected_component: "linux-kernel".into(),
                affected_version: "3.15–6.8-rc1".into(),
                kev_listed: true,
                mitre_tactic: "Privilege Escalation".into(),
                mitre_technique: "Exploitation for Privilege Escalation".into(),
                mitre_technique_id: "T1068".into(),
                description: "A use-after-free vulnerability in the nf_tables component of the Linux kernel's netfilter subsystem allows local privilege escalation to root.".into(),
                published: "2024-01-31".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2024-1086".into()],
            },
            ThreatCorrelation {
                id: "tc-003".into(),
                cve_id: "CVE-2023-44487".into(),
                title: "HTTP/2 Rapid Reset DDoS Attack".into(),
                cvss_score: 7.5,
                severity: "HIGH".into(),
                affected_component: "nginx".into(),
                affected_version: "< 1.25.3".into(),
                kev_listed: true,
                mitre_tactic: "Impact".into(),
                mitre_technique: "Endpoint Denial of Service".into(),
                mitre_technique_id: "T1499.003".into(),
                description: "The HTTP/2 protocol allows a denial of service because request cancellation can reset many streams quickly, exploited in the wild as the largest DDoS attacks ever recorded.".into(),
                published: "2023-10-10".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2023-44487".into()],
            },
            ThreatCorrelation {
                id: "tc-004".into(),
                cve_id: "CVE-2024-21626".into(),
                title: "runc Container Escape via /proc/self/fd Leak".into(),
                cvss_score: 8.6,
                severity: "HIGH".into(),
                affected_component: "runc".into(),
                affected_version: "< 1.1.12".into(),
                kev_listed: false,
                mitre_tactic: "Defense Evasion".into(),
                mitre_technique: "Escape to Host".into(),
                mitre_technique_id: "T1611".into(),
                description: "runc leaks an internal file descriptor to the container init process, allowing an attacker to gain access to the host filesystem and achieve container escape.".into(),
                published: "2024-01-31".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2024-21626".into()],
            },
            ThreatCorrelation {
                id: "tc-005".into(),
                cve_id: "CVE-2024-27198".into(),
                title: "JetBrains TeamCity Authentication Bypass".into(),
                cvss_score: 9.8,
                severity: "CRITICAL".into(),
                affected_component: "teamcity-server".into(),
                affected_version: "< 2023.11.4".into(),
                kev_listed: true,
                mitre_tactic: "Initial Access".into(),
                mitre_technique: "Exploit Public-Facing Application".into(),
                mitre_technique_id: "T1190".into(),
                description: "Authentication bypass in JetBrains TeamCity allows unauthenticated attackers to perform admin actions including RCE via arbitrary plugin uploads.".into(),
                published: "2024-03-04".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2024-27198".into()],
            },
            ThreatCorrelation {
                id: "tc-006".into(),
                cve_id: "CVE-2023-38545".into(),
                title: "curl SOCKS5 Heap Buffer Overflow".into(),
                cvss_score: 9.8,
                severity: "CRITICAL".into(),
                affected_component: "curl".into(),
                affected_version: "7.69.0–8.3.0".into(),
                kev_listed: false,
                mitre_tactic: "Execution".into(),
                mitre_technique: "Exploitation for Client Execution".into(),
                mitre_technique_id: "T1203".into(),
                description: "A heap-based buffer overflow in the SOCKS5 proxy handshake in libcurl could allow remote code execution when a long hostname is used.".into(),
                published: "2023-10-11".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2023-38545".into()],
            },
            ThreatCorrelation {
                id: "tc-007".into(),
                cve_id: "CVE-2024-4577".into(),
                title: "PHP-CGI Argument Injection on Windows".into(),
                cvss_score: 9.8,
                severity: "CRITICAL".into(),
                affected_component: "php".into(),
                affected_version: "< 8.3.8".into(),
                kev_listed: true,
                mitre_tactic: "Execution".into(),
                mitre_technique: "Command and Scripting Interpreter".into(),
                mitre_technique_id: "T1059.004".into(),
                description: "In PHP installations running as CGI, certain character sequences can bypass previous CVE-2012-1823 protections, allowing argument injection leading to RCE.".into(),
                published: "2024-06-06".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2024-4577".into()],
            },
            ThreatCorrelation {
                id: "tc-008".into(),
                cve_id: "CVE-2023-46604".into(),
                title: "Apache ActiveMQ RCE via ClassPathXmlApplicationContext".into(),
                cvss_score: 10.0,
                severity: "CRITICAL".into(),
                affected_component: "activemq".into(),
                affected_version: "< 5.18.3".into(),
                kev_listed: true,
                mitre_tactic: "Execution".into(),
                mitre_technique: "Exploitation of Remote Services".into(),
                mitre_technique_id: "T1210".into(),
                description: "Apache ActiveMQ is vulnerable to Remote Code Execution via the OpenWire protocol, allowing attackers to execute arbitrary shell commands via crafted class loading.".into(),
                published: "2023-10-27".into(),
                references: vec!["https://nvd.nist.gov/vuln/detail/CVE-2023-46604".into()],
            },
        ]
    }
}
