use anyhow::Result;
use serde::{Deserialize, Serialize};
use reqwest::{Client, header::{HeaderMap, HeaderValue, AUTHORIZATION, CONTENT_TYPE}};

#[derive(Serialize)]
pub struct ScanRequest {
    pub intent: String,
    pub payload: String,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ScanResponse {
    pub risk: String,
    pub analysis: String,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ReviewResponse {
    pub status: String,
    pub feedback: String,
}

pub struct NovaClient {
    client: Client,
    api_key: String,
    endpoint: String,
}

impl NovaClient {
    pub async fn new() -> Result<Self> {
        let api_key = std::env::var("NOVA_API_KEY").unwrap_or_else(|_| "d4ee932b-2f90-406c-ac7a-1c5d379389db".to_string());
        
        let mut headers = HeaderMap::new();
        headers.insert(CONTENT_TYPE, HeaderValue::from_static("application/json"));
        if !api_key.is_empty() {
            let auth_val = format!("Bearer {}", api_key);
            if let Ok(val) = HeaderValue::from_str(&auth_val) {
                headers.insert(AUTHORIZATION, val);
            }
        }

        let client = Client::builder()
            .default_headers(headers)
            .build()?;

        Ok(Self {
            client,
            api_key,
            // Typical hackathon proxy endpoint for Nova Lite
            endpoint: "https://api.nova.amazon.com/v1/chat/completions".to_string(), 
        })
    }

    pub async fn scan(&self, req: ScanRequest) -> Result<ScanResponse> {
        let prompt = format!(
            "Security analysis for Agentic Engine.\nIntent: {}\nPayload:\n{}\n\nClassify risk: LOW | MEDIUM | HIGH and explain the specific reasoning, potential attack paths, and what the payload attempts to do.",
            req.intent,
            req.payload
        );

        let system_prompt = "You are an expert cybersecurity analyst acting as a Security Gate (Nova Shield) for an AI agent. Evaluate the given intent and payload for security risks. Your response MUST contain the words 'Risk Level: HIGH', 'Risk Level: MEDIUM', or 'Risk Level: LOW' depending on the threat. Provide a detailed analysis.";

        let body = serde_json::json!({
            "model": "nova-2-lite-v1",
            "messages": [
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.1
        });

        // Fast fail if no key is provided, returning a dummy to not break the UI
        if self.api_key.is_empty() {
             return Ok(ScanResponse {
                 risk: "LOW".into(),
                 analysis: "Simulated analysis: No API Key provided for Nova. Allowing by default.".into(),
             })
        }

        let response = self
            .client
            .post(&self.endpoint)
            .json(&body)
            .send()
            .await?;

        if !response.status().is_success() {
             let status = response.status();
             let err_text = response.text().await.unwrap_or_default();
             return Err(anyhow::anyhow!("Nova API Error {}: {}", status, err_text));
        }

        let parsed_response: serde_json::Value = response.json().await?;
        
        // Extract from OpenAI schema: choices[0].message.content
        let analysis_text = parsed_response["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("Failed to parse Nova response")
            .to_string();

        Ok(ScanResponse {
            risk: extract_risk(&analysis_text),
            analysis: analysis_text,
        })
    }

    pub async fn review_code(&self, original_code: &str, patched_code: &str) -> Result<ReviewResponse> {
        let prompt = format!(
            "Compare the original code and the patched code.\n\nOriginal Code:\n{}\n\nPatched Code:\n{}\n\nDoes the patched code introduce any secondary vulnerabilities or fail to fix the original issue? Respond strictly with 'APPROVED' if it is perfect, or 'REJECTED' with an explanation if it is flawed.",
            original_code, patched_code
        );

        let system_prompt = "You are an elite Security Auditor and Code Reviewer. Your job is to rigorously review code patches generated by another AI. You must find any flaws, logic bombs, or regressions. Begin your response with either APPROVED or REJECTED.";

        let body = serde_json::json!({
            "model": "nova-2-lite-v1",
            "messages": [
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.1
        });

        if self.api_key.is_empty() {
             return Ok(ReviewResponse {
                 status: "APPROVED".into(),
                 feedback: "Simulated review: No API Key provided for Nova. Auto-approving patch.".into(),
             })
        }

        let response = self
            .client
            .post(&self.endpoint)
            .json(&body)
            .send()
            .await?;

        if !response.status().is_success() {
             let status = response.status();
             let err_text = response.text().await.unwrap_or_default();
             return Err(anyhow::anyhow!("Nova API Error {}: {}", status, err_text));
        }

        let parsed_response: serde_json::Value = response.json().await?;
        let feedback_text = parsed_response["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("APPROVED")
            .trim()
            .to_string();

        let status = if feedback_text.to_uppercase().contains("REJECTED") {
            "REJECTED".to_string()
        } else {
            "APPROVED".to_string()
        };

        Ok(ReviewResponse {
            status,
            feedback: feedback_text,
        })
    }
}

fn extract_risk(text: &str) -> String {
    let upper_text = text.to_uppercase();
    if upper_text.contains("HIGH") || upper_text.contains("RISK LEVEL: HIGH") {
        "HIGH".into()
    } else if upper_text.contains("MEDIUM") || upper_text.contains("RISK LEVEL: MEDIUM"){
        "MEDIUM".into()
    } else {
        "LOW".into()
    }
}
